services:
  client:
    image: node:latest
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
    working_dir: /client
    container_name: client
    command: sh -c "npm install && npm run dev"
