services:
  client:
    image: node:latest
    ports:
      - 4200:4200
    volumes:
      - ./client:/client
    working_dir: /client
    container_name: client
    command: sh -c "npm install && npm run dev"
    depends_on:
      - server
      - db
  server:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ./server:/server
    working_dir: /server
    container_name: server
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "zahlenzauber_db"

volumes:
  mysql-data: